import type { AnalysisResult } from "../llm/schemas";

export function exportToMarkdown(result: AnalysisResult): string {
  const { summary, questions, outline, goNoGo } = result;
  const lines: string[] = [];

  lines.push("# RFP Radar Analysis");
  lines.push(`> Generated by RFP Radar. AI output may be wrong; verify against the original RFP.`);
  lines.push("");

  // --- Executive Summary ---
  lines.push("---");
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(`**Document Type:** ${summary.meta.doc_type}`);
  if (summary.meta.industry_guess.length > 0) {
    lines.push(`**Industry:** ${summary.meta.industry_guess.join(", ")}`);
  }
  lines.push(`**Confidence:** ${Math.round(summary.meta.confidence * 100)}%`);
  lines.push("");

  if (summary.key_dates.length > 0) {
    lines.push("### Key Dates");
    for (const d of summary.key_dates) {
      const dateStr = d.date ?? "TBD";
      const timeStr = d.time ? ` · ${d.time}` : "";
      lines.push(`- **${d.label}:** ${dateStr}${timeStr} *(${d.source})*`);
    }
    lines.push("");
  }

  if (summary.scope.length > 0) {
    lines.push("### Scope");
    for (const s of summary.scope) lines.push(`- ${s}`);
    lines.push("");
  }

  if (summary.deliverables.length > 0) {
    lines.push("### Deliverables");
    for (const d of summary.deliverables) lines.push(`- ${d}`);
    lines.push("");
  }

  if (summary.constraints.length > 0) {
    lines.push("### Constraints");
    for (const c of summary.constraints) lines.push(`- ${c}`);
    lines.push("");
  }

  if (summary.evaluation_criteria.length > 0) {
    lines.push("### Evaluation Criteria");
    for (const e of summary.evaluation_criteria) {
      const weight = e.weight ? ` (${e.weight})` : "";
      lines.push(`- **${e.criterion}**${weight} — *${e.source}*`);
    }
    lines.push("");
  }

  if (summary.submission_requirements.length > 0) {
    lines.push("### Submission Requirements");
    for (const r of summary.submission_requirements) lines.push(`- ${r}`);
    lines.push("");
  }

  if (summary.risk_indicators.length > 0) {
    lines.push("### Risk Indicators");
    for (const r of summary.risk_indicators) {
      lines.push(`- **[${r.severity}]** ${r.item} — *${r.source}*`);
    }
    lines.push("");
  }

  if (summary.assumptions.length > 0) {
    lines.push("### Working Assumptions");
    for (const a of summary.assumptions) lines.push(`- ${a}`);
    lines.push("");
  }

  if (summary.unknowns.length > 0) {
    lines.push("### Unknowns");
    for (const u of summary.unknowns) lines.push(`- ${u}`);
    lines.push("");
  }

  // --- Clarifying Questions ---
  lines.push("---");
  lines.push("## Clarifying Questions");
  lines.push("");

  const categories = [...new Set(questions.questions.map((q) => q.category))];
  for (const cat of categories) {
    lines.push(`### ${cat}`);
    const catQuestions = questions.questions.filter((q) => q.category === cat);
    for (const q of catQuestions) {
      lines.push(`**Q:** ${q.question}`);
      lines.push(`*Why it matters:* ${q.why_it_matters}`);
      lines.push(`*Reference:* ${q.reference}`);
      lines.push("");
    }
  }

  // --- Proposal Outline ---
  lines.push("---");
  lines.push("## Proposal Outline");
  lines.push("");
  lines.push("> Draft scaffold — requires your specifics.");
  lines.push("");

  for (const section of outline.outline) {
    lines.push(`### ${section.section_title}`);
    if (section.source_hint) lines.push(`*From RFP:* ${section.source_hint}`);
    for (const note of section.notes) lines.push(`- ${note}`);
    lines.push("");
  }

  if (outline.assumptions_needed.length > 0) {
    lines.push("### Assumptions Needed");
    for (const a of outline.assumptions_needed) lines.push(`- ${a}`);
    lines.push("");
  }

  // --- Go/No-Go ---
  lines.push("---");
  lines.push("## Go / No-Go Assessment");
  lines.push("");

  const rec = goNoGo.recommendation;
  const recLabel = rec === "GO" ? "✅ GO" : rec === "MAYBE" ? "⚠️ MAYBE" : "❌ NO-GO";
  lines.push(`**Recommendation: ${recLabel}**`);
  lines.push("");

  if (goNoGo.top_reasons.length > 0) {
    lines.push("### Top Reasons");
    for (const r of goNoGo.top_reasons) lines.push(`- ${r}`);
    lines.push("");
  }

  if (goNoGo.risk_flags.length > 0) {
    lines.push("### Risk Flags");
    for (const f of goNoGo.risk_flags) {
      lines.push(`- **[${f.severity}]** ${f.flag} — *${f.reference}*`);
    }
    lines.push("");
  }

  if (goNoGo.what_to_resolve.length > 0) {
    lines.push("### Questions to Resolve Before Go");
    for (const q of goNoGo.what_to_resolve) lines.push(`- ${q}`);
    lines.push("");
  }

  return lines.join("\n");
}
